# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1loJlctVi1VgRmhgKi6s7BIt__Kcjmv9u
"""

txt = " 	Moscow 	"
str_clean = txt.strip()
print(f"From weather report, {str_clean} is too cold most of the times")

from tabulate import tabulate
# custom function for pretty print
def pretty_print(title, df, n):
   print(f"\n{title}:")
   print(tabulate(df.head(n), headers="keys", tablefmt="psql"))

import pandas as pd

data = {'state': ["CA", "CA", "TX", "NC", "SC"], 'deaths': [6, 11, 4, 5, 9]}
df = pd.DataFrame(data)

# Group by 'state' and count the number of unique 'deaths'
df2 = df.groupby('state')['deaths'].nunique().reset_index(name='unique_death_counts')

# Display the resulting DataFrame
print(df2.head(10))

import pandas as pd
import csv

# Create DataFrame
df = pd.DataFrame({"date": ["2018-09-24"], "ret": [0.00013123989025119056]})

# Write to CSV with specific options
df.to_csv("out.csv", sep=',', escapechar='\\', quoting=csv.QUOTE_ALL, index=None)

import pandas as pd

# Create the DataFrame
df = pd.DataFrame({"date": ["2018-09-24"], "ret": [0.00013123989025119056]})

# Write to CSV without quoting and using space as a separator
df.to_csv('out.csv', sep=' ', quoting=csv.QUOTE_NONE, index=None)

num_person = 10
print("Type of num_person:", type(num_person))